version: '3.7'
services:
    redis:
        image: redis:latest
        command: redis-server --requirepass ${REDIS_PASS}
        ports:
        - ${REDIS_PORT}:6379
        volumes:
        - ./persistence/redis:/data
        hostname: redis
        restart: always